### ISSUE TITLE
Port to Android?

### ISSUE THREAD

**Issue by paradoxewan** [NukeAlchemist/blupi#1]
Any thoughts on porting to Android platform for car head units?

**Comment by NukeAlchemist** [comment]
Frankly, the project stalled a few months ago when the requirements for proper functionality ballooned the scope and cost of the project by a few orders of magnitude. So, no, not really much of a point to port it.

From my research and work; the project would require the following:
    - a web repository with an auto-updated database of radio frequencies to scan
    - 2x $200 specialty radio tuners
    - a usb gps receiver
    - either a Raspberry Pi 3, or (more likely), an Odoid XU4
    - wifi coverage where the car is parked overnight (for updating the database)

As you can imagine, it’d be hard to get anyone on-board with something so expensive.

-Evan

**Comment by raymiec** [comment]
There will be a version for android coming soon that will work with Tetra (Most of EU), I already have the driver done for connecting to the RTL-SDR. Initial testing seems to work pretty good.   Also if anyone wants to contribute give me a shout.
